package main

import gobyex "github.com/shabin5785/learnings/go-by-example/code"

func main() {
	// gobyex.Variables()
	// gobyex.For()
	// gobyex.Switch()
	// gobyex.Array()
	// gobyex.Slice()
	// gobyex.Map()
	// gobyex.Fns()
	// gobyex.Closure()
	// gobyex.Recursion()
	// gobyex.Pointers()
	// gobyex.Structs()
	// gobyex.Methods()
	// gobyex.Interfaces()
	// gobyex.Errors()
	// gobyex.GoRoutine()
	// gobyex.Channels()
	// gobyex.ChannelsSync()
	// gobyex.SelectIt()
	// gobyex.TimeOut()
	// gobyex.BetterChannel()
	// gobyex.CloseChannel()
	// gobyex.RangeChannel()
	// gobyex.Timer()
	// gobyex.Ticker()
	// gobyex.WorkerPool()
	// gobyex.WaitGroup()
	// gobyex.RateLimiting()
	// gobyex.AtomicCounter()
	// gobyex.MutexFn()
	// gobyex.StateFul()
	// gobyex.Sorting()
	// gobyex.DeferFn()
	gobyex.RecoverFn()

}
